NDefines.NCountry.COUNTRY_DEVELOPMENT_SCALE = 3000 -- 600

NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 3  --5
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 25

NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.01 -- 0.007
NDefines.NCountry.EDICTS_COST_INCREASE = 0.5 -- 2

NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 1.5 --2
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 1.5 --2

NDefines.NEconomy.DECREASE_AUTONOMY_STEP = 0  -- 25
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 0  -- 25
NDefines.NEconomy.CAPITAL_MAX_AUTONOMY = 25 -- 0



NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.35 --0.25

