NDefines.NCountry.COUNTRY_DEVELOPMENT_SCALE = 3000 -- 600

NDefines.NCountry.INSTITUTION_BONUS_FROM_IMP_DEVELOPMENT = 3  --5
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 25

NDefines.NEconomy.DECREASE_AUTONOMY_STEP = 0  -- 25
NDefines.NEconomy.INCREASE_AUTONOMY_STEP = 0  -- 25

